### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
@Dman95 Could you please review?

**Comment by piper4hire** [comment]
yeah, review it!!

also review the nonfunctional unsubscribe feature.

-S

**Comment by rex4539** [comment]
Closing due to no interest.

**Comment by piper4hire** [comment]
I have no interest in this spam.

**Comment by votemikejones** [comment]
No one asked me, I’m interested.

**Pull request closed without merging**
